name: Inbound
favicon: null
layout_spectrum: 0.2901089172810316
typography_spectrum: 0.6902194935828447
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6754520088434219
  lightness: 0.47327463049441576
  saturation: 0.18265896383672953
  rhythmicContrast: 0.26832613348960876
purpose: []
